name: GitHub Action

on:
  push:
    branches:
      - main

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo
        uses: actions/checkout@v2
        
      - name: Mostrar mensaje
        run: echo "Hola, este es un flujo de trabajo simple en GitHub Actions"